{
 "title": "RabbitMQ Monitoring",
 "description": "Rabbitmq stats and alerting using Telegraf",
 "tags": [
  "rabbitmq",
  "telegraf"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "15s, 30s, 1m, 5m, 1h, 6h, 1d" },
   {
    "name": "node",
    "label": "Node",
    "query": "{\"find\": \"terms\", \"field\": \"tags.node\", \"query\": \"name:rabbitmq_node\"}"
   },
   {
    "name": "vhost",
    "label": "Virtual Host",
    "query": "{\"find\": \"terms\", \"field\": \"tags.vhost\", \"query\": \"name:rabbitmq_queue\"}"
   },
   {
    "name": "queue",
    "label": "Queue",
    "query": "{\"find\": \"terms\", \"field\": \"tags.queue\", \"query\": \"name:rabbitmq_queue\"}"
   },
   {
    "name": "exchange",
    "label": "Exchange",
    "query": "{\"find\": \"terms\", \"field\": \"tags.exchange\", \"query\": \"name:rabbitmq_exchange\"}"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$node",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "repeat": "node",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.running",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: rabbitmq_node && tags.node: $node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Channels",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.channels",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: rabbitmq_overview",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.connections",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: rabbitmq_overview",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.consumers",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: rabbitmq_overview",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Nodes Up",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.node",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.running",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: rabbitmq_node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Queues",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.queues",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: rabbitmq_overview",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Exchanges",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.exchanges",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: rabbitmq_overview",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Exchange", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Incoming Messages",
   "type": "graph",
   "description": "Detailed message stats (see section above) for publishes from channels into this exchange.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Messages" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.exchange",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "tags.vhost",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.messages_publish_in",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: rabbitmq_exchange && tags.exchange: $exchange && tags.vhost: $vhost",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Outgoing Messages",
   "type": "graph",
   "description": "Detailed message stats for publishes from this exchange into queues",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Messages" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.exchange",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "tags.vhost",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.messages_publish_out",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: rabbitmq_exchange && tags.exchange: $exchange && tags.vhost: $vhost",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Messages per Queue",
   "type": "graph",
   "description": "Total messages in the queue",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Messages" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.queue",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "tags.vhost",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.messages",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: rabbitmq_queue && tags.node: $node && tags.queue: $queue && tags.vhost: $vhost",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Messages Delivered",
   "type": "graph",
   "description": "Count of messages delivered in acknowledgement mode to consumers",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Messages" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.queue",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "tags.vhost",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.messages_deliver",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: rabbitmq_queue && tags.node: $node && tags.queue: $queue && tags.vhost: $vhost",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Messages Acknowledged",
   "type": "graph",
   "description": "Number of messages delivered to clients and acknowledged",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Messages" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.queue",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "tags.vhost",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.messages_ack",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: rabbitmq_queue && tags.node: $node && tags.queue: $queue && tags.vhost: $vhost",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Messages Unacknowledged",
   "type": "graph",
   "description": "Number of messages delivered to clients but not yet acknowledged",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Messages" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.queue",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "tags.vhost",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.messages_unack",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: rabbitmq_queue && tags.node: $node && tags.queue: $queue && tags.vhost: $vhost",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Messages Published",
   "type": "graph",
   "description": "Count of messages published",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Messages" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.queue",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "tags.vhost",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.messages_publish",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: rabbitmq_queue && tags.node: $node && tags.queue: $queue && tags.vhost: $vhost",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Messages Get",
   "type": "graph",
   "description": "Count of messages delivered in acknowledgement mode in response to basic.get",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Messages" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.queue",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "tags.vhost",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.messages_deliver_get",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: rabbitmq_queue && tags.node: $node && tags.queue: $queue && tags.vhost: $vhost",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Messages Ready",
   "type": "graph",
   "description": "Number of messages ready to be delivered to clients",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Messages" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.queue",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "tags.vhost",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.messages_ready",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: rabbitmq_queue && tags.node: $node && tags.queue: $queue && tags.vhost: $vhost",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Messages Redeliver",
   "type": "graph",
   "description": "Count of subset of messages in deliver_get which had the redelivered flag set",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Messages" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.queue",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "tags.vhost",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.messages_redeliver",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: rabbitmq_queue && tags.node: $node && tags.queue: $queue && tags.vhost: $vhost",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Free disk space",
   "type": "graph",
   "description": "Disk free space in bytes",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.node",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.disk_free",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: rabbitmq_node && tags.node: $node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Free file descriptors",
   "type": "graph",
   "description": "File descriptors available",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "File Descriptors" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.node",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.fd_used",
       "id": "1",
       "inlineScript": "doc['fields.fd_total'].value - _value",
       "meta": {},
       "settings": {
        "script": {
         "inline": "doc['fields.fd_total'].value - _value"
        }
       },
       "type": "avg"
      }
     ],
     "query": "name: rabbitmq_node && tags.node: $node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "description": "Memory used in bytes",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.node",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.mem_used",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: rabbitmq_node && tags.node: $node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Erlang processes",
   "type": "graph",
   "description": "Number of Erlang processes in use",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short", "label": "Processes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.node",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.proc_used",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: rabbitmq_node && tags.node: $node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Erlang queue",
   "type": "graph",
   "description": "Average number of Erlang processes waiting to run",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 47 },
   "yaxes": [
    { "format": "short", "label": "Processes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.node",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.run_queue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: rabbitmq_node && tags.node: $node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Sockets used",
   "type": "graph",
   "description": "File descriptors used as sockets",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 47 },
   "yaxes": [
    { "format": "short", "label": "File Descriptors" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.node",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.sockets_used",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: rabbitmq_node && tags.node: $node",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}