{
 "title": "Elasticsearch",
 "description": "Display Elasticsearch key metrics from Telegraf",
 "tags": [
  "elasticsearch",
  "telegraf"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "15s, 30s, 1m, 5m, 1h, 6h, 1d" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "{\"find\": \"terms\", \"field\": \"tags.cluster_name\", \"query\": \"name:elasticsearch_os\"}"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "{\"find\": \"terms\", \"field\": \"tags.node_name\", \"query\": \"name:elasticsearch_os\"}"
   }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Status",
   "type": "singlestat",
   "description": "On the shard level, a red status indicates that the specific shard is not allocated in the cluster, yellow means that the primary shard is allocated but replicas are not, and green means that all shards are allocated. The index level status is controlled by the worst shard status. The cluster status is controlled by the worst index status.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.status_code",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: \"elasticsearch_cluster_health\" && tags.name: $cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Cluster Status Histogram",
   "type": "graph",
   "description": "On the shard level, a red status indicates that the specific shard is not allocated in the cluster, yellow means that the primary shard is allocated but replicas are not, and green means that all shards are allocated. The index level status is controlled by the worst shard status. The cluster status is controlled by the worst index status.",
   "gridPos": { "h": 3, "w": 8, "x": 4, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "fields.status_code",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "name: \"elasticsearch_cluster_health\" && tags.name: $cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "singlestat",
   "description": "Instances running Elasticsearch in ${cluster:csv} cluster(s)",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.number_of_nodes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: \"elasticsearch_cluster_health\" && tags.name: $cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Data Nodes",
   "type": "singlestat",
   "description": "Data nodes hold data and perform data related operations such as CRUD, search, and aggregations in ${cluster:csv} cluster(s)",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.number_of_data_nodes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: \"elasticsearch_cluster_health\" && tags.name: $cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "singlestat",
   "description": "Number of metadata changes that occur faster than ${cluster:csv} cluster(s) master node process",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.number_of_pending_tasks",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: \"elasticsearch_cluster_health\" && tags.name: $cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Shards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Active Shards",
   "type": "singlestat",
   "description": "Number of shards (primary and replicas) in ${cluster:csv} cluster(s) open indices",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.active_shards",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: \"elasticsearch_cluster_health\" && tags.name: $cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Active Primary Shards",
   "type": "singlestat",
   "description": "Number of primary shards in ${cluster:csv} cluster(s) open indices",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.active_primary_shards",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: \"elasticsearch_cluster_health\" && tags.name: $cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Initializing Shards",
   "type": "singlestat",
   "description": "Number of just created shards in ${cluster:csv} cluster(s)",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.initializing_shards",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: \"elasticsearch_cluster_health\" && tags.name: $cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Relocating Shards",
   "type": "singlestat",
   "description": "Number of shards in ${cluster:csv} cluster(s) that are currently moving from one node to other",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.relocating_shards",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: \"elasticsearch_cluster_health\" && tags.name: $cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Unassigned Shards",
   "type": "singlestat",
   "description": "Number of shards in ${cluster:csv} cluster(s) that not assigned to node",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.unassigned_shards",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: \"elasticsearch_cluster_health\" && tags.name: $cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "CPU usage for the whole system",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent", "label": "CPU Usage" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.node_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.cpu_percent",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: \"elasticsearch_os\" && tags.cluster_name: $cluster && tags.node_name: $node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Percentage of used memory",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "percent", "label": "Memory Usage" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.node_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.mem_used_percent",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: \"elasticsearch_os\" && tags.cluster_name: $cluster && tags.node_name: $node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "description": "Percentage of used disk",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "percentunit", "label": "Disk Usage" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.node_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.total_available_in_bytes",
       "id": "1",
       "inlineScript": "1 - (_value / doc[\"fields.total_total_in_bytes\"].value)",
       "meta": {},
       "settings": {
        "script": {
         "inline": "1 - (_value / doc[\"fields.total_total_in_bytes\"].value)"
        }
       },
       "type": "avg"
      }
     ],
     "query": "name: \"elasticsearch_fs\" && tags.cluster_name: $cluster && tags.node_name: $node",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Open File Descriptors",
   "type": "singlestat",
   "description": "Number of opened file descriptors associated with the current process",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.open_file_descriptors",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: \"elasticsearch_process\" && tags.cluster_name: $cluster && tags.node_name: $node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Received Data",
   "type": "graph",
   "description": "Amount of data received in cluster communication",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 20 },
   "yaxes": [
    { "format": "bytes", "label": "Size" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.node_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.rx_size_in_bytes",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: \"elasticsearch_transport\" && tags.cluster_name: $cluster && tags.node_name: $node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "HTTP Connections Rate",
   "type": "graph",
   "description": "Number of HTTP connections currently open",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "Connections/s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.node_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.current_open",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: \"elasticsearch_http\" && tags.cluster_name: $cluster && tags.node_name: $node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Sent Data",
   "type": "graph",
   "description": "Amount of data sent in cluster communication",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 26 },
   "yaxes": [
    { "format": "bytes", "label": "Size" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.node_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.tx_size_in_bytes",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: \"elasticsearch_transport\" && tags.cluster_name: $cluster && tags.node_name: $node",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Documents and Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Documents Indexing Rate",
   "type": "graph",
   "description": "Number of documents currently being indexed to an index",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "Documents/s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.node_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.indexing_index_current",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: \"elasticsearch_indices\" && tags.cluster_name: $cluster && tags.node_name: $node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Indexing Latency",
   "type": "graph",
   "description": "Documents index to an index latency",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 33 },
   "yaxes": [
    { "format": "ms", "label": "Latency" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.node_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.indexing_index_time_in_millis",
       "id": "1",
       "inlineScript": "_value / doc[\"fields.indexing_index_total\"].value",
       "meta": {},
       "settings": {
        "script": {
         "inline": "_value / doc[\"fields.indexing_index_total\"].value"
        }
       },
       "type": "avg"
      }
     ],
     "query": "name: \"elasticsearch_indices\" && tags.cluster_name: $cluster && tags.node_name: $node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Search Rate",
   "type": "graph",
   "description": "Number of searches on primary shards",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "Searches/s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.node_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.search_query_current",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: \"elasticsearch_indices\" && tags.cluster_name: $cluster && tags.node_name: $node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Search Latency",
   "type": "graph",
   "description": "Latency on querying primary shard",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 33 },
   "yaxes": [
    { "format": "ms", "label": "Latency" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.node_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.search_query_time_in_millis",
       "id": "1",
       "inlineScript": "_value / doc[\"fields.search_query_total\"].value",
       "meta": {},
       "settings": {
        "script": {
         "inline": "_value / doc[\"fields.search_query_total\"].value"
        }
       },
       "type": "avg"
      }
     ],
     "query": "name: \"elasticsearch_indices\" && tags.cluster_name: $cluster && tags.node_name: $node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Documents Count (with replicas)",
   "type": "graph",
   "description": "Number of documents in the ${cluster:csv} cluster(s)",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short", "label": "Documents" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.node_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.docs_count",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: \"elasticsearch_indices\" && tags.cluster_name: $cluster && tags.node_name: $node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Documents Deleting Rate",
   "type": "graph",
   "description": "Number of documents deleted",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 43 },
   "yaxes": [
    { "format": "short", "label": "Documents/s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.node_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.docs_deleted",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: \"elasticsearch_indices\" && tags.cluster_name: $cluster && tags.node_name: $node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Documents Merging Rate",
   "type": "graph",
   "description": "Number of documents currently being merged",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 43 },
   "yaxes": [
    { "format": "short", "label": "Merges/s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.node_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.merges_current_docs",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: \"elasticsearch_indices\" && tags.cluster_name: $cluster && tags.node_name: $node",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Caches", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Field Data Memory Size",
   "type": "graph",
   "description": "Size of fielddata cache",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.node_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.fielddata_memory_size_in_bytes",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: \"elasticsearch_indices\" && tags.cluster_name: $cluster && tags.node_name: $node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Field Data Evictions",
   "type": "graph",
   "description": "Number of evictions from the fielddata cache",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short", "label": "Evictions/s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.node_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.fielddata_evictions",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: \"elasticsearch_indices\" && tags.cluster_name: $cluster && tags.node_name: $node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Query Cache Size",
   "type": "graph",
   "description": "Memory used by query cache",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "bytes", "label": "Size" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.node_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.query_cache_memory_size_in_bytes",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: \"elasticsearch_indices\" && tags.cluster_name: $cluster && tags.node_name: $node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Query Cache Evictions Rate",
   "type": "graph",
   "description": "Rate of query cache evictions",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 64 },
   "yaxes": [
    { "format": "short", "label": "Evictions/s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.node_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.query_cache_evictions",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: \"elasticsearch_indices\" && tags.cluster_name: $cluster && tags.node_name: $node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Query Cache Hits Rate",
   "type": "graph",
   "description": "Rate of query cache hits",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "bytes", "label": "Hits/s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.node_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.query_cache_hit_count",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: \"elasticsearch_indices\" && tags.cluster_name: $cluster && tags.node_name: $node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Query Cache Misses Rate",
   "type": "graph",
   "description": "Rate of query cache misses",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 64 },
   "yaxes": [
    { "format": "short", "label": "Misses/s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.node_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.query_cache_miss_count",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: \"elasticsearch_indices\" && tags.cluster_name: $cluster && tags.node_name: $node",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Throttling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Indexing Throttling",
   "type": "graph",
   "description": "Time indexing waited due throttling",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.node_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.indexing_throttle_time_in_millis",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: \"elasticsearch_indices\" && tags.cluster_name: $cluster && tags.node_name: $node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Recovery Throttling",
   "type": "graph",
   "description": "Time recovery waited due throttling",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.node_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.recovery_throttle_time_in_millis",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: \"elasticsearch_indices\" && tags.cluster_name: $cluster && tags.node_name: $node",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Heap Used",
   "type": "graph",
   "description": "Amount of memory used by JVM heap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "bytes", "label": "Heap" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.node_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.mem_heap_used_in_bytes",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: \"elasticsearch_jvm\" && tags.cluster_name: $cluster && tags.node_name: $node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "graph",
   "description": "Number of active threads in JVM",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 86 },
   "yaxes": [
    { "format": "short", "label": "Threads" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.node_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.threads_count",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: \"elasticsearch_jvm\" && tags.cluster_name: $cluster && tags.node_name: $node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "graph",
   "description": "Number of major GCs that collect old generation objects and number of minor GCs that collects young generation objects in JVM",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short", "label": "GC/s" }
   ],
   "targets": [
    {
     "alias": "Old - {{tags.node_name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.node_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.gc_collectors_old_collection_count",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: \"elasticsearch_jvm\" && tags.cluster_name: $cluster && tags.node_name: $node",
     "timeField": "@timestamp"
    },
    {
     "alias": "Young - {{tags.node_name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.node_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.gc_collectors_young_collection_count",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: \"elasticsearch_jvm\" && tags.cluster_name: $cluster && tags.node_name: $node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "graph",
   "description": "Time spent on major GCs that collect old generation objects and on minor GCs that collects young generation objects in JVM",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "alias": "Old - {{tags.node_name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.node_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.gc_collectors_old_collection_time_in_millis",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: \"elasticsearch_jvm\" && tags.cluster_name: $cluster && tags.node_name: $node",
     "timeField": "@timestamp"
    },
    {
     "alias": "Young - {{tags.node_name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.node_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fields.gc_collectors_young_collection_time_in_millis",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: \"elasticsearch_jvm\" && tags.cluster_name: $cluster && tags.node_name: $node",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}